const { 
  TEAM_ID,
  TEAM_PASSWORD, 
  WSDL_ACTIVITY,
  WSDL_ACTIVITY_TYPE,
  WSDL_BRANCH,
  WSDL_ROOM,
  WSDL_RESERVATION
} = process.env

module.exports = {
  TEAM_ID,
  TEAM_PASSWORD,
  WSDL_ACTIVITY,
  WSDL_ACTIVITY_TYPE,
  WSDL_BRANCH,
  WSDL_ROOM,
  WSDL_RESERVATION
}