const { 
  TEAM_ID,
  TEAM_PASSWORD, 
  WSDL_ACTIVITIES,
  WSDL_ACTIVITY_TYPES,
  WSDL_BRANCHES,
  WSDL_ROOMS,
  WSDL_RESERVATIONS,
  WSDL_CUSTOMER
} = process.env

module.exports = {
  TEAM_ID,
  TEAM_PASSWORD,
  WSDL_ACTIVITIES,
  WSDL_ACTIVITY_TYPES,
  WSDL_BRANCHES,
  WSDL_ROOMS,
  WSDL_RESERVATIONS,
  WSDL_CUSTOMER
}